name: Build and Release Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Decode Base64 Keystore
        run: |
          echo "${{ secrets.BASE64_ENCODED_KEYSTORE }}" | base64 -d > keystore.jks

      - name: Grant execute permissions to gradlew
        run: |
          chmod +x ./gradlew

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore keystore.jks \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            ${{ secrets.KEYSTORE_ALIAS }}

      - name: Verify and Align APK
        run: |
          zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk \
            app/build/outputs/apk/release/app-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Upload Release APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk
